### ISSUE TITLE
Laden eines gelöschten Datensatzes verhindern

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.cas#183]
Wenn man in der WFC-Anwendung einen Datensatz löscht und der Index nicht automatisch neu geladen wird ist es möglich, den eben gelöschten Datensatz wieder ins Detail zu laden.

Das ist verwirrend und sollte verhindert werden.

Es sollte eine entsprechende Fehlermeldung geworfen werden.

**Comment by splitcells** [comment]
Das muss man über den SQL-Code machen,
indem man bspw. keine Werte zurück gibt oder ein raiserror einbaut:
```
raiserror('ADO | 25 | msg.DailyClosingExistingLoan | Es sind noch unstornierte Leihgaben vorhanden.', 16, 1) with seterror
return -1 
```

**Comment by splitcells** [comment]
@janiak-minova Konnte ich die Frage klären?

**Comment by janiak-minova** [comment]
Prinzipiell ja, das Verhalten ist aber noch nicht umgesetzt.

**Comment by splitcells** [comment]
@janiak-minova Damit ist aber das CAS-Ticket erstmal durch,
da hier auch keine Liste von Prozeduren/Views vorhanden ist,
welche korrigiert werden sollen.

**Comment by janiak-minova** [comment]
Es so zu lösen, dass generell ein Fehler geworfen wird, wenn ein gelöschter Datensatz gewählt wird, ist nicht möglich?

**Comment by splitcells** [comment]
Wir können grundsätzlich prüfen,
ob bei einer SQL-Ausfhührung eine LastAction-Spalte vorhanden ist
und dann entsprechend filtern.

Allerdings ist damit das Problem nur verschoben und man muss jetzt immer eine LastAction-Spalte zurückgeben.
Das heißt, dass der SQL-Code dann trotzdem LastAction beachten muss.

Zudem ist nicht jeder gelöschter Datensatz irrelevant.
Was macht man bei einem Join von nicht gelöscht nach gelöscht Daten?
Häufig gibt man den gelöschten Datensatz trotzdem zurück,
aber nicht immer.

Wenn das CAS jetzt dies bearbeiten müsste,
müsste es letzlich mehrer LastActions gleichtzeitig verarbeiten können,
was hoch wahrscheinlich fehleranfällig und fallspezifisch sein wird.

**Comment by splitcells** [comment]
Für ein solches Feature bräuchten wir ein vollständiges Konzept.

**Comment by splitcells** [comment]
Nur mal als Beispiel:
Die Prozedur xpcasReadWorkingTime liest einen Eintrag anhand des KeyLongs.
Woher weiss das CAS, dass der Datensatz gelöscht ist?

**Comment by janiak-minova** [comment]
Ich dachte eben über die LastAction Spalte.

Aktuell bekommt bei einer Anfrage auf einen bereits gelöschten Datensatz eine Antwort, in der alles außer dem KeyLong null/0/false ist:

{"outputParameters":{"name":"outputParameters","columns":[{"name":"KeyLong","type":"INTEGER","outputType":"OUTPUT"},{"name":"EmployeeKey","type":"INTEGER","outputType":"OUTPUT"},{"name":"ServiceContractKey","type":"INTEGER","outputType":"OUTPUT"},{"name":"OrderReceiverKey","type":"INTEGER","outputType":"OUTPUT"},{"name":"ServiceObjectKey","type":"INTEGER","outputType":"OUTPUT"},{"name":"ServiceKey","type":"INTEGER","outputType":"OUTPUT"},{"name":"BookingDate","type":"INSTANT","outputType":"OUTPUT"},{"name":"StartDate","type":"INSTANT","outputType":"OUTPUT"},{"name":"EndDate","type":"INSTANT","outputType":"OUTPUT"},{"name":"RenderedQuantity","type":"DOUBLE","outputType":"OUTPUT"},{"name":"ChargedQuantity","type":"DOUBLE","outputType":"OUTPUT"},{"name":"Description","type":"STRING","outputType":"OUTPUT"},{"name":"Spelling","type":"BOOLEAN","outputType":"OUTPUT"}],
"rows":[{"values":["n-823","n-0","n-0","n-0","n-0","n-0",null,null,null,"d-0.0","d-0.0",null,"b-false"]}]},"returnCodes":[1],"returnCode":0}

Das wird dann versucht ins Detail zu schreiben, wobei es für den Nutzer aussieht als würde nichts passieren. Ich könnte mir halt vorstellen, dass das verwirrend ist. 
Erst nach einem Neuladen des Index verschwindet der gelöschte Eintrag.

Aber wenn es nicht möglich ist, da eine allgemeine einfache Lösung zu finden ist es denk ich auch nicht schlimm.

**Comment by splitcells** [comment]
Wie gesagt, man bräuchte ein Konzept.
Aber es wird nicht so funktionieren,
dass man es dann auf SQL-Seite einfach komplett vergessen kann.

Da wird man auf jeden Fall was anpassen müssen und dazu müsste man etwas definieren.

**Comment by splitcells** [comment]
Ich denke, dass das Thema erstmal tot ist.
