### ISSUE TITLE
Rechtekonzept für Oiltanking

### ISSUE THREAD

**Issue by CE7** [minova-afis/aero.minova.cas#186]
Es wird Benutzer geben, die eingeschränkte Rechte haben aus die Maske Invoice.xml anbetrifft. 

Was genau hier die Anforderungen sind muss noch mit dem Kunden besprochen werden.

**Comment by CE7** [comment]
- [ ] Anlegen der Benutzer mit entsprechenden Rechten 
- [ ] Tests für diese Benutzer anlegen

**Comment by STKLEBA** [comment]
Im SIS soll es 5 Rollen geben, wie im ersten Bild dargestellt. Die Rollen soll die Rechte aus Bild 2 und 3 haben.

<img width="427" alt="Screenshot 2021-09-07 at 16 34 36" src="https://user-images.githubusercontent.com/89842301/132363395-51c6a869-9f9e-40bc-87b1-c44b8f3d92db.png">
<img width="714" alt="Screenshot 2021-09-07 at 16 35 47" src="https://user-images.githubusercontent.com/89842301/132363410-342e7acc-aa66-48d7-9c60-e6fe48c9214b.png">
<img width="703" alt="Screenshot 2021-09-07 at 16 35 56" src="https://user-images.githubusercontent.com/89842301/132363421-83ae5b63-e085-4bbe-9e70-c897849e53cd.png">

**Comment by splitcells** [comment]
- [ ] Wir bräuchten einen lesenden AD-Zugriff.

**Comment by weber-minova** [comment]
Privilegien zugeteilt für folgene Nutzer:

Betriebsleiter:
- [ ]  Gut - ServiceObject
- [ ] Leistungsart - Service
- [ ] Firma - Company
- [ ] Kunde - ServiceProvider
- [ ] MwSt - Vat
- [ ] Journal Vorlage - JournalTemplate
- [ ] Stundenerfassung - WorkingTime
- [ ] Journal - Journal
- [ ] Kontrakt - ServiceContract
- [ ] Staffelsatz - Graduation / GraduationStep
- [ ] Vorgang - Invoice
- [ ] Statistik - Statistic

Buchhaltung:
- [ ]  Gut - ServiceObject
- [ ] Leistungsart - Service
- [ ] Firma - Company
- [ ] Kunde - ServiceProvider
- [ ] MwSt - Vat
- [ ] Journal Vorlage - JournalTemplate
- [ ] Stundenerfassung - WorkingTime
- [ ] Journal - Journal
- [ ] Kontrakt - ServiceContract
- [ ] Staffelsatz - Graduation / GraduationStep
- [ ] Vorgang - Invoice
- [ ] Statistik - Statistic

Marketing:
- [ ]  Gut - ServiceObject
- [ ] Leistungsart - Service
- [ ] Firma - Company
- [ ] Kunde - ServiceProvider
- [ ] MwSt - Vat
- [ ] Journal Vorlage - JournalTemplate
- [ ] Stundenerfassung - WorkingTime
- [ ] Journal - Journal
- [ ] Kontrakt - ServiceContract
- [ ] Staffelsatz - Graduation / GraduationStep
- [ ] Vorgang - Invoice
- [ ] Statistik - Statistic

ZBF/BAMS (admin)
- [ ]  Gut - ServiceObject
- [ ] Leistungsart - Service
- [ ] Firma - Company
- [ ] Kunde - ServiceProvider
- [ ] MwSt - Vat
- [ ] Journal Vorlage - JournalTemplate
- [ ] Stundenerfassung - WorkingTime
- [ ] Journal - Journal
- [ ] Kontrakt - ServiceContract
- [ ] Staffelsatz - Graduation / GraduationStep
- [ ] Vorgang - Invoice
- [ ] Statistik - Statistic

Read Only:
- [ ]  Gut - ServiceObject
- [ ] Leistungsart - Service
- [ ] Firma - Company
- [ ] Kunde - ServiceProvider
- [ ] MwSt - Vat
- [ ] Journal Vorlage - JournalTemplate
- [ ] Stundenerfassung - WorkingTime
- [ ] Journal - Journal
- [ ] Kontrakt - ServiceContract
- [ ] Staffelsatz - Graduation / GraduationStep
- [ ] Vorgang - Invoice
- [ ] Statistik - Statistic

**Comment by weber-minova** [comment]
Service.ServiceGroup und OrderReveiver.ReceivableAccounts noch hinzugefügt.

**Comment by weber-minova** [comment]
@STKLEBA ich bräuchte die Namen in Verbindung zu den Spalten (also welche LDAP-Gruppe ist Marketing, welche Gruppe ist Betriebsleiter, etc), damit ich sie in das init-Skript eintragen kann.
Die init-Skripte sind so weit vorbereitet (solange keine neuen Prozeduren/Views dazukommen), die Namen der UserGruppen müssten nur noch angepasst werden.
Wenn die dann eingetragen sind, sollte das dann auch out of the box funktionieren.

**Comment by weber-minova** [comment]
Die Nutzergruppen stehen im Kundenprojekt in den jeweiligen init-Skripten.
Die Admin-Benutzergrupp wird nach dem Setup automatisch angelegt.
