### ISSUE TITLE
Einfache Methode für detaillierte Request-Logging

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.cas#187]
Zur Zeit haben wir keine einfache Methode, um **alle** HTTP-Requests zu loggen.
Auch nicht authorisierte HTTP-Request sollten einfach logbar sein,
um Autorisierung-Probleme untersuchen zu können.

**Comment by weber-minova** [comment]
"Das brauchen wir erstmal nicht" - Martins Avots, 2022
