### ISSUE TITLE
Privilegien-Masken testen.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.cas#205]
Sind in dem App-Projekt von diesem Repo definiert.
Funktionieren diese überhaupt?

**Comment by weber-minova** [comment]
Die Masken an sich funktionieren.
Vielleicht wäre es noch sinnvoll für die Verbindungen User-UserGroup und UserGroup-UserPrivilege jeweils eine Optionpage zu erstellen, mit denen man den User zur Gruppe und die Rechte zur Gruppe zuweisen kann.

**Comment by splitcells** [comment]
Wäre sehr gut.
