### ISSUE TITLE
Dokumenten-Speicher definieren.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.cas#238]
Das CAS sollte den Pfad für den Dokumenten-Speicher vorschreiben,
damit nicht für jede einzelne Erweiterung der Pfad gesetzt werden muss.
Zudem sollte der FileService eine Methode bereitstellen,
mit der für jede Erweiterung ein individuelle Ordner bereitgestellt wird,
ohne dass die Erweiterung dies selber definieren muss.

**Comment by weber-minova** [comment]
"Wird sich ergeben, wenn wir es brauchen" - M.A.

Der Pfad wird vom CAS im FileService inzwischen bereitgestellt.
