### ISSUE TITLE
SqlProcedureController nach ProcedureController umbennenen.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.cas#261]
Wir wollen in Zukunft von Stored-Procedure zu Extensions weggehen.
Im Source-Code, ist es aber dann nicht besonders hilfreich,
wenn die dazugeghörigen Controller mit SQL-Anfangen und damit quasi 'Werbung' für SQL machen.

**Comment by weber-minova** [comment]
Ist jetzt zu spät
