### ISSUE TITLE
Register-Extension

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#267]
Es könnte für den CAS eine weitere Funktionalität geben, mit welcher sich andere Dienste beim CAS registrieren können (solange sie natürlich die benötigten Anmeldeinformationen haben).

Dazu würden drei neue Tabellen (noch Working Title) benötigt werden:

- xtcasCASService (KeyLong, SerivceName, Hostname, Port): Mit dieser Tabelle kann der CAS herausfinden, zu welcher Adresse der Dienst gehört und wohin der CAS die Datenpakete schicken muss.
- xtcasProcedureNewsfeed (ProzedurName,Tabelle): Mit dieser Tabelle wird vermerkt, welche Prozeduren Änderungen auf bestimmten Tabellen machen.
- xtcasNewsfeedListener (CASServiceKey, Tabelle): In dieser Tabelle wird hinterlegt, welche Services auf welche Tabellen horchen und informiert werden müssen, wenn diese geändert werden.

Beim Start des Externen Dienstes, kann dieser sich über eine 'registerOnStartup'-Methode beim CAS registrieren, wodurch in der xtcasCASService und in der xtcasNewsfeedListener ein Eintrag angelegt wird:
![Register](https://user-images.githubusercontent.com/75690564/160996612-fb57157b-19fa-42a6-9d44-346f488bd4c9.png)

Im laufenden Betrieb prüft der CAS nach jedem Prozeduraufruf, ob der Prozedurname in der xtcasProcedureNewsfeed vorhanden ist und falls dies der Fall ist, werden alle 'zuhörenden' Dienste kontaktiert. Beispiel für die Lieferscheine:
![LieferscheinBeispiel](https://user-images.githubusercontent.com/75690564/160997195-b4b61226-7081-49a3-9e3d-1d384c411d85.png)

So muss nicht bei jedem neuen Dienst, der mit dem CAS kommunizieren soll, die application.properties des CAS abgeändert werden. Denn bei jeder Änderung der application.properties, muss das CAS neu gestartet werden. Dies führt zu unnötiger Down Time. 
Außerdem müssten so auch die Ports und URLs der Dienste nicht an mehreren Stellen gepflegt werden.

**Comment by splitcells** [comment]
👏

* xtcasCASService.ServiceName -> KeyText
* xtcasProcedureNewsfeed und xtcasNewsfeedListener: alle Tabellen sollten einen KeyLong haben.
* Es soll bei Updates nicht die gesamte Tabelle übertragen werden, sondern nur der geänderte Eintrag (da müssten wir noch spezifizieren, wie man den herausfindet, aber erstmal sollten wir das Prinzip mit @ingraban absprechen.)
