### ISSUE TITLE
Alter/Create-Fehler beim Setup

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#284]
Manchmal kann der SetupService eine View nicht anlegen. (Letztes Beispiel: xvcorVehicleMeterIndex)

Laut Martins werden Views und Prozeduren im Setup-Prozess erst leer angelegt und dann mit dem Script, das im sql-Ordner liegt, überschrieben.

**Comment by weber-minova** [comment]
Das App-Projekt, dass installiert wurde, war aero.minova.truck in der Version 12.0.0

**Comment by splitcells** [comment]
Das Projekt hat kein Dockerfile.

**Comment by weber-minova** [comment]
Der Fehler war in der aero.minova.Vehicle Setup-xml.
Es wurde versucht die View als Script und nicht als View einzuspielen.
