### ISSUE TITLE
Fehlermeldung verbessern.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.cas#287]
ControllerExceptionHandler Zeile 126: Wir bräuchten heir eine echte Fehlermeldzung (`errorMessage = errorMessage.substring(errorMessage.indexOf("msg."));`) und nicht eine einfach nur eine OutOfBoundsException:
* Was ist die errorMessage?

**Comment by weber-minova** [comment]
Duplikat zu https://github.com/minova-afis/aero.minova.cas/issues/274
