### ISSUE TITLE
Setup-Fehler beim Ausführen über den Browser anzeigen

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.cas#292]
Der setup-Befehl kann über den Browser ausgeführt werden.
Wenn beim setup-Befehl ein Fehler auftritt erscheint trotzdem "Setup successfully completed!".
Man muss erst die Logs auf einen Fehler überprüfen. 
Es wäre schön, wenn die Fehlermeldung schon im Browser angezeigt wird.

**Comment by splitcells** [comment]
Doppeltes Ticket: #285
