### ISSUE TITLE
value Long < - > Json ?

### ISSUE THREAD

**Issue by DvonHolten** [minova-afis/aero.minova.cas#300]
warum tauchen überall in der Value-Welt Longs auf, nicht jedoch in ValueSerializer/ValueDeserializer ?

**Comment by DvonHolten** [comment]
in der Value-Klasse gibt es Code, der anhand des eingestellten types den passenden Typ zurückgibt. Dort und in DataType.java ist auch Long enthalten. In ValueSerializer und ValueDesierializer werden alle Typen in JsonPrimitves gewandelt - Long fällt durchs Raster.

**Comment by DvonHolten** [comment]
ich hab ne Handvoll kleiner Tipp-Fehler beseitigt, kann mir jemand commit-Recht auf dieses Projekt geben?

**Comment by splitcells** [comment]
Das ist historisch gewachsen.
Man hat wahrscheinlich erst mit DataType konzeptionel angefangen und
dann die De/Serializer implementiert, aber für Longs keinen echten Anwendungsfall gehabt.
Da die switches basierened auf den DataType im Standardfall keinen Fehler schmeißen ist das nicht aufgefallen.

**Comment by DvonHolten** [comment]
bis jemand mal ne Long-column schickt

**Comment by splitcells** [comment]
Der einfachste weg ist es einen Fork auf Github zu erstellen und darüber einen Pull-Request zu erstellen.
Ich würde dazu eine kurze Anleitung machen.

**Comment by DvonHolten** [comment]
hab schon mit branches in movementservice gearbeitet - hab in cas kein Recht zum Push und zum Fork

**Comment by splitcells** [comment]
Da das CAS öffentlich ist (open source) sollte man keine gesonderte Rechte dafür benötigen.

**Comment by splitcells** [comment]
Danke für den Pull-Request.
Leider hat anscheinend eine automatisierte Formatierung einige ungewollte Änderung getätigt.
