### ISSUE TITLE
Extensions in com.minova- Paketen

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#302]
Das CAS unterstützt/findet bisher nur Extensions, welche mit 'aero.minova' anfangen.
--> @ComponentScan("aero.minova") & @EntityScan("aero.minova") in der Main-Klasse *CoreApplicationSystemApplication*

Falls wir mal eine Extension in einem Kundenprojekt haben(, die ja mit 'com.minova' anfangen), würde das CAS diese Extension nicht finden.

Soll das CAS dementsprechend angepasst werden oder soll in der Doku darauf hingewiesen werden, dass ***explizit*** 'aero.minova' bei Extensions verwendet werden  muss?

**Comment by splitcells** [comment]
Extensions von Kunden-Projekten sollten mit `com.minova` anfangen, da es sonst nur Verwirrung stiften wird.
Man könnte beide Pfade einfügen `@ComponentScan({"aero.minova","com.minova"})` oder alles erlauben.
Würde erstmal nur `com.minova` zu ComponentScan hinzufügen.
