### ISSUE TITLE
Von 2.2.5 auf aktuelles SpringBoot (2.6.x) updaten

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.cas#319]
ALS: Entwickler
MÖCHTE ICH: die aktuellsten 3rd-Party Bibliotheken verwenden 
SO DASS: die potentiellen Angriffsvektoren durch ungepatchte Sicherheitslücken reduziere

ALS: Entwickler
MÖCHTE ICH: Meine Software hinsichtlich Schwachstellen automatisiert untersuchen lassen
SO DASS: Eine qualifizierte Aussage über den Ist-Zustand und die weitere Entwicklung im Blick habe

* [x] CAS
* [x] SAM-Scharr
* [ ] Movement-Service

**Comment by weber-minova** [comment]
Das CAS hat inzwischen das aktuelle Spring Boot (2.7.0).

**Comment by scholz-afis** [comment]
> Das CAS hat inzwischen das aktuelle Spring Boot (2.7.0).

PR für 2.7.2 liegt unter https://github.com/minova-afis/aero.minova.cas/pull/348

**Comment by scholz-afis** [comment]
@kos366 @weber-minova Ich habe den Spring Boot Update vom Movement Service nach https://github.com/minova-afis/aero.minova.tta.movementservice/issues/62 ausgelagert.
