### ISSUE TITLE
Datenbankzugriffe aus den Controllern in eigene Klasse

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#320]
Dadurch, dass die Datenbankzugriffe momentan in den Controllern sind, gibt es unschöne circulare Abhängigkeiten.

Außerdem entspricht es nicht der normalen Spring-Archtiktur: 
Controller -> Service -> Repository

**Comment by splitcells** [comment]
Außerdem entspricht es nicht der normalen Spring-Archtiktur. -> Das ist Fehlen von JPA, was ein eigenes Thema ist.

**Comment by weber-minova** [comment]
Aber man könnte zumindest die Methoden, welche auf die Datenbank zugreifen, in eine eigene ServiceKlasse auslagern.

**Comment by splitcells** [comment]
Das müssten wir zusammen besprechen,
ich denke, da ist ein Missverständnis.

**Comment by weber-minova** [comment]
Was im ProcedureController als Hauptlogik übrig bleiben würde:
* Privilegienprüfung
* Extensions
* Aufruf vom SQL Service (bestehende Methoden deprecaten und auf neuen Service verweisen lassen)
* QueueService
