### ISSUE TITLE
OpenAPI einbinden.

### ISSUE THREAD

**Issue by splitcells** [minova-afis/aero.minova.cas#337]
Bisher ist nur die neue attachement-API definiert: https://github.com/minova-afis/aero.minova.cas.openapi.api
* #331 ist das ursprüngliche Ticket.
* [ ] OpenAPI public setzen und Lizenz angeben. @splitcells
* [ ] OpenAPI-Nutzung anstatt von cas.api für CAS dokumentieren. @splitcells (https://github.com/minova-afis/aero.minova.sam.scharr/blob/bad-1252-file-manager/client/aero.minova.sam.helper/src/aero/minova/sam/helper/web/AttachmentsWebClient.java)
* [x] Properties dokumentieren. @scholz-afis
* [x] S3-Integrations-Tests standardmäßig nur auf GitHub testen. @scholz-afis 

Siehe dazu auch das Issue **Konsistente Verwaltung von Dateien auf persistenten Speichern** (https://github.com/minova-afis/aero.minova.cas.plugin.attachments/issues/16)

**Comment by scholz-afis** [comment]
Beim PR https://github.com/minova-afis/aero.minova.sam.scharr/pull/22 zum Issue https://github.com/minova-afis/aero.minova.sam.scharr/issues/14 hat sich herausgestellt, dass für eine saubere Lösung eines Datei-Uploads (z.B. S3, Azure Storage, NAS) mit entsprechendem Eintrag in eine DB Tabelle eigentlich das Design-Pattern `Transactional Outbox` notwendig wäre.

Es wäre daher sinnvoll eine allgemeine Lösung hierzu zu erarbeiten, die folgende Features enthält:
- WFC-Helper, der der `BEFORESAVE` Methode die Dateien vorab zum CAS-Endpunkt `/attachments` überträgt.
- Methoden `xtDeleteAttachment`, `xtInsertAttachment` und `xtUpdateAttachment` als CAS-Extension, um das `Transactional Outbox` Pattern auf den Tabellen namens `xtAttachments` sowie `xtAttachmentsOutbox` umzusetzen.
- Die Tabelle `xtAttachments` enthält die Spalten `ReferenceKey` und `ReferenceTableKey`, um das Anzeigen von hochgeladenen Dateien in anderen Tabellen (via `Join`) einzublenden.
- Die Bestandteile (WFC-Helper, CAS-Extension, Tabellen-Beschreibung) des Features könnten als ein separates Repository gekapselt werden.

**Comment by splitcells** [comment]
Leider bin ich mehr als voll ausgelastet.
Ich denke, dass es am besten ist, wenn ihr das ganze als Extension/Plugin für euch entwirft und entwickelt.
Wenn das Feature dann so weit ist, könnte man es als Teil des Standard-CAS machen,
aber das wäre dann eine getrennte Aufgabe.

**Comment by splitcells** [comment]
Diese API wird doch erstmal als Plugin implementiert.
