### ISSUE TITLE
Andere Authentifizierungsmethoden unterstützen

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#352]
Bisher unterstützen wir nur Basic Authentication.

Wäre es vielleicht sinnvoll in Zukunft auch z.B. OAuth(2)  oder andere tokenbasierte Authentifizierungsmethoden zu unterstützen?

**Comment by splitcells** [comment]
Das wird sich ergeben, sobald @scholz-afis es für sein Cloud-Projekt benötigt.
