### ISSUE TITLE
@RestControllerAdvice - One to rule 'em all?

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.cas#381]
In https://github.com/minova-afis/aero.minova.cas/blob/master/service/src/main/java/aero/minova/cas/ControllerExceptionHandler.java gibt es einen uneingeschränkten `@RestControllerAdvice`. D.h. sobald man diese `cas-service` Dependency im eigenen Source verwendet, schnappt der CAS ControllerExceptionHandler (fast) alle Exceptions weg, sofern diese etwas mit REST-Controllern zu tun haben.

Ist das so gewünscht?
- Falls **"nein"**, könnte der ControllerExceptionHandler mit `@RestControllerAdvice("aero.minova.cas.controller")` auf seine eigenen Controller eingeschränkt werden. Siehe dazu auch https://reflectoring.io/spring-boot-exception-handling/
- Falls **"ja"**, gibt es für andere CAS-Plugins mit eigenem ExceptionHandler für REST-Requests noch eine andere Möglichkeit die Exceptions aus den eigenen Controller selbst zu verarbeiten:
```
@Primary
@RestControllerAdvice("aero.minova.cas.plugin.sam.adapter.in.web")
```

Cc: @janiak-minova, @HohmW

**Comment by splitcells** [comment]
Es ist beabsichtig, dass der ExceptionHandler erstmal alle Exceptions abfängt,
da die meisten Plugin daran nicht denken werden.

Dass sollte man dokumentieren.

Ansonsten, kann man den [ControllerExceptionHandler.java](https://github.com/minova-afis/aero.minova.cas/blob/master/service/src/main/java/aero/minova/cas/ControllerExceptionHandler.java) eventuell so anpassen, dass er für die Plugins generel besser passt.

**Comment by scholz-afis** [comment]
Aus meiner Sicht ist die Frage beantwortet.
