### ISSUE TITLE
Doku zum Erstellen von Extensions

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#440]

**Comment by martins-1992** [comment]
Dazu bitte die vorhandene Extension-Doku erweitern, soweit es nicht zu Problemen führt, damit eine Sache nicht an verschiedenen Stellen dokumentiert ist: https://github.com/minova-afis/aero.minova.cas/blob/master/service/doc/adoc/extensions.adoc

**Comment by martins-1992** [comment]
Darauf könnte man auch verweisen: https://github.com/minova-afis/aero.minova.default.template.app

**Comment by weber-minova** [comment]
Jupp, ist in meiner bisherigen Erweiterung schon drin
