### ISSUE TITLE
Syntax Fehler in tVersion10 

### ISSUE THREAD

**Issue by Bauer-David** [minova-afis/aero.minova.cas#534]
**Beschreibung:**
Ich habe mit der CAS Version 12.60.1 versucht ein setup in dem Projekt aero.minova.traveexpenses auszuführen. Nach einer Sekunde kam dann ein Fehler.

**Screenshots:**

Postman Ausgabe:
"s-java.lang.RuntimeException: java.lang.RuntimeException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Schema \"SYS\" not found; SQL statement:\nselect b.name tablename, a.name columnname, a.is_nullable, t.name datatype, case a.user_type_id when 231 then a.max_length / 2 else a.max_length end as Length, c.name DefaultName, c.definition DefaultValue, a.collation_name from sys.all_columns a inner join sys.tables b on a.object_id = b.object_id left join sys.default_constraints c on a.default_object_id = c.object_id left join sys.types t on t.user_type_id = a.user_type_id order by b.name [90079-214]"

Terminal Fehlermeldung:
<img width="1614" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/61147549/235603335-424d9f8a-531a-4f34-8ce5-45bf2641e64c.png">

**Betriebssystem:**
MAC

**Comment by scholz-afis** [comment]
@Bauer-David Verwendest Du die SpringBoot Properties, um Deine Datenbank zu konfigurieren? Weil eine `H2` wirst Du wohl eher nicht einsetzen, oder?

```
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=false;databaseName=foobar
spring.datasource.username=sa
spring.datasource.password=*******
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.show-sql=true
spring.jpa.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
```

**Comment by Bauer-David** [comment]
Das ist mein Docker run

docker run \
  --name=travelexpenses \
  --publish=8084:8084 \
  --env login_dataSource='admin' \
  --env aero_minova_database_url='jdbc:sqlserver://host.docker.internal;encrypt=false;databaseName=TRAVELEXPENSES' \
  --env aero_minova_database_user_name='sa' \
  --env aero_minova_database_user_password='Minova+0' \
  --env logging_level_root=DEBUG \
  --env aero.minova.check.message.intervall='0 0 0 20 1 6' \
  --env APPLICATION_STORAGE_AWS_ACCESS_KEY="00fb73797d0cddfaa235“ \
 --env APPLICATION_STORAGE_AWS_SECRET_ACCESS_KEY="DA788vHt+XJRkI52Lon5+dMpjELDklYieQnHRZIs“ \
 --env APPLICATION_STORAGE_AWS_BUCKET_NAME="comminovadevbad“ \
 --env APPLICATION_STORAGE_AWS_REGION="de“ \
 --env APPLICATION_STORAGE_AWS_ENDPOINT_OVERRIDE="https://s3-de-central.profitbricks.com" \
 --env APPLICATION_SAM_SERVER_BASE_URI=/travelexpenses \
 --env APPLICATION_SERVER_BASE_URI=/ \
  minova/travelexpenses

Mit der Version 12.59.0 ging es noch alles. Ist irgendwo nieder geschrieben, dass es ab der Version anders eingestellt werden muss?

**Comment by scholz-afis** [comment]
@Bauer-David Steht im Changelog von CAS https://github.com/minova-afis/aero.minova.cas/blob/main/CHANGELOG.adoc
```
## [12.60.0] -- 2023-04-21
* Update auf SpringBoot 3.0.5.
* Korrektur der Connectionfreigabe.
* AuthorizationTest ausbessern (Tabelle leeren, damit andere Tests nicht das Ergebnis beeinflussen)
* `aero_minova_database_` properties entfernen (sind durch `spring.datasource.` abgedeckt)
* Fehlermeldung bei Laden von Privilegien verbessern
```

.... und wir wissen ja alle, dass Dokus so wichtig sind, da die ja jeder liest.

**Comment by martins-1992** [comment]
Dokus erlauben es für Doku-Authoren Dinge zu vergessen oder zu suchen,
und somit zu chillen.

**Comment by Bauer-David** [comment]
Dann hat sich das erledigt
