### ISSUE TITLE
Release-Stände bei kundenspezifischen CAS Projekten

### ISSUE THREAD

**Issue by scholz-afis** [minova-afis/aero.minova.cas#563]
Ist-Zustand:
---
* CAS ist eine Backend-Applikation primär für das WFC Frontend geschrieben. Das WFC ist primär eine *Eclipse RCP* Applikation.
* CAS soll mit *Extensions* erweiterbar sein, um gffs. kundenspezifische Anpassungen auf dem Backend zur Verfügung zu stellen
* CAS soll als einziges Backend für WFC Endpunkte zur Verfügung stellen, durch das sich WFC kundenspezifische Anpassung für sich selbst (Frontend) herunterladen kann und ausführt. 
* CAS ist ein Multi-Module Projekt mit einer Parent-POM im Hauptverzeichnis
* CAS basiert auf SpringBoot, daher wird indirekt auf die SpringBoot-BOM verwiesen
  * Die Hierarchie zum CAS Module `cas.service` verläuft:
     * `maven.root`
        * `maven.spring.root`
           * `cas.parent`
              * `cas.service`
  * Die Hierarchie zum CAS Module `cas.app` wird in `cas.parent` referenziert, aber `cas.app` hat **nicht** `cas.parent` als Parent sondern dessen Hierarchie verläuft anders. (*Maven* warnt auch vor diesem Problem):
     * `maven.root`
        * `app.parent`
           * `cas.app`
  * Außerdem gibt es in dem Projekt ein weiteres Verzeichnis `client`, das eine POM enthält, die überhaupt nichts mit dieser Backend-Applikation zu tun hat und auch keine Parent POM hat
 
Probleme innerhalb vom CAS Projekt:
---
* Für SpringBoot wird regelmäßig aktualisiert. Die Aktualisierungen enthalten neben Verbesserungen und Bugfixes auch das Schliessen von Sicherheitslücken (Vulnerabilities).
* Damit CAS ein neues SpringBoot Release verwenden kann, muss folgende Repository-Hierarchie jeweils einzeln und in absteigender Reihenfolge released werden:  
        * `maven.spring.root`
            * `cas.parent`
               * ...
* Damit CAS auf ein neues *Maven* Plugin, das nicht unmittelbar mit SpringBoot zu tun hat, zugreifen kann, muss folgende Repository-Hierarchie jeweils einzeln released werden:  
     * `maven.root`
        * `maven.spring.root`
            * `cas.parent`
               * ...
        * `app.parent`
            * `cas.app`
 
Probleme bei kundenspezifischen Erweiterungen:
---
* Auf CAS basierende (einfache) Kundenprojekte können (und haben auch) folgenden Aufbau: 
     * `maven.root`
        * `maven.spring.root`
            * `cas.parent`
               * ... 
            * `cas.plugin.attachments`
                * `cas.plugin.attachments.extension` (abhängig von `cas.service`)
            * `cas.plugin.sam` (abhängig von `cas.plugin.attachments.extension`)
            * `sam`
               * `sam.cas.extension` (abhängig von `cas.api`, `cas.service`, `cas.plugin.attachments.extension`, `cas.plugin.sam`)
            * `sam.kunde`
        * `app.parent` 
            * `cas.app`
            * `cas.plugin.attachments.app` (abhängig von `cas.app`, `app.i18n`)
            * `sam.app` (abhängig von `cas.app`, `app.i18n`, `cas.plugin.attachments.app`)
            * `sam.kunde.app` (abhängig von `sam.app`)
     * Außerdem sogenannte *Clients* (für das WFC Frontend) in den Repositories `cas`, `cas.plugin.attachments`, `sam`
* Es gibt ein Maven-Plugin, das für das Ziel `package` alle Abhängigkeiten (JARs) unter `target` im Verzeichnis `docker-extension-layer` zusammenkopiert. Diese JARs werden später im `CLASSPATH` der laufenden Applikation zur Verfügung stehen.
    * Falls die Extensions (evtl. auch `app`) bei der Erstellung unterschiedliche Releases der Parent-Hierarchien gehabt haben, dann stehen im `CLASSPATH` unterschiedliche Release-Stände zur Verfügung, die von der JVM zufällig ausgewählt werden, z.B.
![Bildschirmfoto 2023-05-17 um 09 57 16](https://github.com/minova-afis/aero.minova.cas/assets/95353437/609b6d32-9f34-4feb-9d68-ac334efe1af4)
![image](https://github.com/minova-afis/aero.minova.cas/assets/95353437/be51f8c2-23c1-4ded-96bf-af23c1f43409)
* Es hängt vom Zielsystem ab, ob eine bekannte Sicherheitslücke bzw. Bug in einer Bibliothek noch existiert oder die aktuellste Bibliothek wird.
* Die Integrationtests der Projekte testen mit Releases von Bibliotheken, die auf dem Produktivsystem potentiell nicht in Verwendung sind.
* Das Plugin `maven-enforcer` kann unterschiedliche Releases von (3rd Party) Libraries nicht erkennen, da das zusammenkopieren von Bibliotheken ausserhalb der konkreten Projekte erfolgt. Die Extensions können ja in sich konsistent sein, nur leider mit unterschiedlichen SpringBoot Releases (2.7, 3.0.1, 3.0.6) in der Parent-Hierarchie.
* Die Erkennung von Releaseunterschieden löst noch nicht das Bauen konsistenter Applikationen, d.h. sämtliche Extensions und CAS selbst, die eine kundenspezifisches CAS verwendet, müssten mit der gleichen `maven.root` und `maven.spring.root` Grundlage immer wieder gebaut und released werden.
   * Ausschließlich dieser definierte Releasestand müsste dann in allen Schichten des Kundenprojekts als Abhängigkeit verwendet und getestet werden.
   * Eine Multilayer-Abhängigkeiten-Architektur ist inkompatibel zu *Continuous Deployment*, kompliziert zu managen und sollte  entfernt werden:

Applikationen und Problematik von Release-Ständen bei anderen Softwarefirmen:
---
* Eine common-Library für grundsätzliche Dinge, z.B. FTP Transfers, E-Mails verschicken
   * Applikationen haben diese als Parent-BOM eingetragen.
* Mikroservices, die nichts miteinander zu tun haben und von z.B. der jeweils aktuellsten SpringBoot-BOM erben und alle andere Abhängigkeiten selbst verwalten.

Problemlösungsmöglichkeiten:
---
* Alle Extensions etc. in CAS einbauen (Big-Ball-of-Mud Prinzip) und alles an alle Kunden ausliefern
   * Die *Applikation* und *Clients* Hierarchien gehören nicht zur Backend Anwendung und sollten aus dem Projekt entfernt werden.
      * *Applikation* und *Clients* müssten über einen anderen Mechanismus aus einem Artifakt-Repository geladen werden.
* Extensions nicht in den CAS einbauen, sondern als entkoppelte Mikroservices bauen, die via REST oder gRPC mit CAS oder direkt mit WFC kommunizieren.
   * Bei Bedarf können Mikroservices eine einzige common-Library einbinden. (Wenn genau ein Mikroservice für E-Mails verschicken zuständig wäre, dann muss niemand anders eine 3rd-Party Bibliotheken ebenfalls dafür managen.)
* *Jigsaw* könnte unterschiedliche Bibliotheksstände evtl. von anderen Programmteilen kapseln, aber damit habe ich noch keine Erfahrungen/Tests gemacht.

**Links:**
* https://github.com/minova-afis/aero.minova.cas/issues/559
* https://github.com/minova-afis/aero.minova.sam/pull/62

**Comment by martins-1992** [comment]
Ist hier noch Handlungsbedarf?
Die Lösung dafür steht in der CAS-Doku: https://github.com/minova-afis/aero.minova.cas/blob/main/service/doc/adoc/extensions.adoc

Was bisher nicht vorhanden ist, ist ein Mechanismus, der erzwingt, dass alle Extensions richtig sind.

**Comment by Bauer-David** [comment]
Ne ist mit unseren Änderungen auch soweit alles behoben

**Comment by Bauer-David** [comment]
> @Bauer-David Es geht darum zukünftig nicht mehr in diese Problematik zu kommen. Setzt aber Disziplin auf der Entwicklerseite voraus, solange es kein Maven-Plugin gibt, dass Scope `provided` prüft und gffs. den Build fehlschlagen läßt.
> 
> @martins-1992 Ja, würde das Problem erstmal beheben, wenn sich jeder an die Spielregeln hält.

Wäre ein solches Plugin verfügbar?
