### ISSUE TITLE
Ganze Transaktionen mit Erweiterungen verarbeiten

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.cas#631]
Ich benötige eine Möglichkeit, ganze Transaktionen von einer CAS-Erweiterung abzufangen und zu bearbeiten.

Fürs TTA13 ist das CAS in erster Linie dafür verantwortlich, die Anfragen vom WFC an die verschiedenen Dienste weiterzuleiten.
Wenn in einer Maske mit Grid gespeichert wird, werden in einer Transaktion sowohl das Speichern der Hauptmaske als auch das Einfügen, Aktualisieren und Löschen von Zeilen im Grid ausgeführt.
Das möchte ich gerne komplett abfangen und auf einmal verarbeiten.

Die Registrierung würde ich ähnlich wie bei den normalen Erweiterungen vornehmen. 
Registriert wird auf den `XSqlProcedureController` mit einem Prozedurnamen. 
Sobald eine Tabelle (oder die Erste?) der Transaktion diesen Namen hat, wird die gesamte Transaktion an die Erweiterung umgeleitet.
Damit funktioniert es so ähnlich wie bei den `FollowUpProcedures`, wo nach dem Ausführen einer Transaktion geprüft wird, ob noch bestimmte Checks nötig sind, in dem die Namen aller Prozeduren kontrolliert werden.

Die Privilegienprüfung muss weiterhin im CAS stattfinden.

@martins-1992, @weber-minova Habt ihr Einwände oder andere Ideen?

Abrechnung={XXX/XXX/XXX/ZPROGRAM}

**Comment by martins-1992** [comment]
Grundsätzlich wäre es in Ordnung, wobei die Erweiterungen dann auch ein Rollback unterstützen sollten.
Wofür braucht ihr das?

**Comment by janiak-minova** [comment]
Ich benötige es für TTA13, da ist CAS nur "Weiterleitung", in der CAS Datenbank wird fast nichts gespeichert.


<img width="643" alt="Bildschirmfoto 2023-07-06 um 10 39 53" src="https://github.com/minova-afis/aero.minova.cas/assets/77741125/57b64515-a849-4177-9d74-2fe43d61d60a">

z.B. Das `SalesProduct` wird in einem anderen Dienst verwaltet und ist dort so über JPA definiert:

```
@Entity
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class SalesProduct {

        @Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "KEYLONG")
	private Long keyLong;

	@Column(name = "KEYTEXT", length = 20)
	private String keyText;

	@Column(name = "DESCRIPTION", length = 100)
	private String description;

	@ManyToMany
	@JoinTable(name = "BLENDING", //
			joinColumns = @JoinColumn(name = "SALESPRODUCTKEY"), //
			inverseJoinColumns = @JoinColumn(name = "STOCKPRODUCTKEY"))
	List<StockProduct> components;

       ....
}
```

Beim Speichern im WFC wird die Tabelle in einer CAS Extension in eben so ein `SalesProduct` umgewandelt und an den Dienst geschickt.

Da die Maske eben ein Grid hat, um die Liste von `components` abzubilden, sieht die Anfrage vom WFC ans CAS z.B. so aus, dass in einer Transaktion die "Hauptmaske" gespeichert wird, und dann verschiedene Zeilen eingefügt, aktualisiert oder gelöscht werden.

```
[
    {
        "id": "transactionParent",
        "table": {
            "name": "xpcorUpdateSalesProduct",
            ....
        }
    },
    {
        "id": "Grid_Components_Insert",
        "table": {
            "name": "xpcorInsertSalesProductComponents",
            ....
        }
    },
    {
        "id": "Grid_Components_Update",
        "table": {
            "name": "xpcorUpdateSalesProductComponents",
            ....
        }
    },
    {
        "id": "Grid_Components_Delete",
        "table": {
            "name": "xpcorDeleteSalesProductComponents",
            ....
        }
    }
]
```

Da man aktuell nur einzelne Prozeduren abfangen kann, muss man also eine Extension auf alle 4 Aufrufe registrieren.
Diese haben keine Infos über die anderen Aufrufe, was es z.B. schwierig macht, die Eingabe zu validieren.
Außerdem muss der andere Dienst für jeden Aufruf einzeln angesprochen werden.

Könnte ich die gesamte Transaktion auf einmal behandeln, müsste ich den Dienst nur einmal anfragen und könnte die Eingabe leicht validieren.

Zu dem Rollback: Das ist ja aktuell eben allgemein ein Problem mit den Erweiterungen. Diese können fast nie zurückgenommen werden.
Auch hier hilft es, die gesamte Transaktion auf einmal zu haben, um sie zu überprüfen und bei ungültiger Eingabe die Aktion gar nicht erst auszuführen.

**Comment by janiak-minova** [comment]
Also grob geht es mir darum, dass Erweiterungen Anfragen, die inhaltlich zusammen gehören, auch in einem bearbeiten können.
Transaktionen gehören eben inhaltlich zusammen -> sollten als Einheit in einer Erweiterung  bearbeitet werden können.

**Comment by martins-1992** [comment]
Könnten wir morgen darüber reden?
