### ISSUE TITLE
Falscher String für Postgres-Datenbanktyp?

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.cas#636]
Im [ProcedureService](https://github.com/minova-afis/aero.minova.cas/blob/main/service/src/main/java/aero/minova/cas/service/ProcedureService.java) ist mir aufgefallen, dass als Wert für Postgres Datenbank `postgresql` angegeben ist.
Dieser wird mit der Datenbank-Art verglichen, die in den application.properties mit `spring.jooq.sql-dialect` angegeben wird.

```
        private static final String POSTGRESQL = "postgresql";

	@org.springframework.beans.factory.annotation.Value("${spring.jooq.sql-dialect:mssql}")
	String databaseKind;

	/**
	 * Speichert im SQl-Session-Context unter `casUser` den Nutzer, der die Abfrage tätigt.
	 *
	 * @param connection
	 *            Das ist die Session.
	 * @throws SQLException
	 *             Fehler beim setzen des Kontextes für die connection.
	 */
	public void setUserContextFor(Connection connection) throws SQLException {
		CallableStatement userContextSetter;
		if (databaseKind.equalsIgnoreCase(POSTGRESQL)) {
			userContextSetter = connection.prepareCall("SET my.app_user = ?;");
		} else {
			userContextSetter = connection.prepareCall("exec sys.sp_set_session_context N'casUser', ?;");
		}
		try {
			userContextSetter.setNString(1, SecurityContextHolder.getContext().getAuthentication().getName());
			userContextSetter.execute();
		} catch (Exception e) {
			customLogger.logError("Error while trying to set user for procedures: ", e);
		} finally {
			userContextSetter.close();
		}
	}
```

Ich habe also `spring.jooq.sql-dialect=postgresql` in den properties eingegeben, bekomme aber beim Starten eine Fehlermeldung, dass dieser Wert nicht gültig ist. 

<img width="1392" alt="Bildschirmfoto 2023-07-11 um 10 09 48" src="https://github.com/minova-afis/aero.minova.cas/assets/77741125/b881f46d-40e2-41f4-8a33-e005bf64dfd8">

Ich weiß nicht, wofür der extra Fall beim `userContextSetter` benötigt wird, mMn wird er aber niemals ausgeführt werden können.
Ist das so gewollt?

**Comment by martins-1992** [comment]
`userContextSetter` wird benötigt, um den Nutzer in den Prozeduren zu bestimmen,
ohne, dass man diesen als Parameter überall durchreichen muss.
Das Setzen funktioniert bei den Datenbank jeweils im Detail anders.

Warum anscheinend ein ungültiger String verwendet wird, weiss ich nicht.
@weber-minova ?
