### ISSUE TITLE
Vorgehen bei Setup & JPA

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#651]
**Frage:**
Die Sache mit dem JPA und CAS ist wohl doch noch nicht ganz durch.

Der ServiceNotifierService ist abhängig von 4 Tabellen und schaltet das CAS ab, wenn diese nicht vorhanden sind.
Die Lösung dafür wäre, die 4 Tabellen einzuspielen, was aber per Setup nicht möglich ist, weil sich das CAS ja einfach abschaltet.
Die 4 Tabellen würden jedoch mit JPA aufgespielt werden, was man über die Property 'spring.jpa.hibernate.ddl-auto=update' einschalten kann.
Danach muss man jedoch die ForeignKeys der xtcas-Tabellen löschen, da man sonst das normale Setup nicht durchführen kann.

Ich habe schon lokal versucht mit meinem Branch die Tabellen-Felder auf denselben Typ zu bringen, aber beim Setup wird trotzdem jedes Mal versucht den FK Constraints von xtcasLuUserPrivilegeUserGroup zu löschen. Mein kläglicher Versuch ist hier: https://github.com/minova-afis/aero.minova.cas/pull/650

Es gibt einen Workaround, wie man es verwenden kann, aber das ist auch keine dauerhafte Lösung: https://github.com/minova-afis/aero.minova.cas/blob/main/doc/adoc/support.adoc#sqlserverexception-ung%C3%BCltiger-objektname-xtcasservicemessagereceiverlogintype

Ich weiß nicht ganz wie wir das lösen können:
1. Ganz auf JPA im CAS verzichten. :(
2. Die alten xml-Tables für die CAS Tabellen weg schmeißen und die JPA Klassen behalten.
3. Eine Named Query verwenden beim Setup, dass bevor die Tabellen eingespielt werden, erst die ForeignKeys nur von den xtcas-Tabellen gelöscht werden. (https://stackoverflow.com/questions/57164662/spring-data-jpa-externalizing-native-queries)
4. Eine Möglichkeit finden, wie das sich CAS beendet, wenn Tabellen fehlen(?)
5. Andere Ideen ...

 @ingraban @martins-1992 Help

**Beispiele:**
Schon passiert bei RAS, SAM SCHARR und Stefan Wild.

Abrechnung={XXX/XXX/XXX/ZANALYSE}

**Comment by martins-1992** [comment]
`Die Lösung dafür wäre, die 4 Tabellen einzuspielen, was aber per Setup nicht möglich ist, weil sich das CAS ja einfach abschaltet.`
-> Man könnte den ServiceNotifierService so anpassen, dass er nicht abstürzt, wenn die notwendigen Tabellen nicht vorhanden sind (ähnlich wie bei der Prozedur-Erweiterung).

**Comment by ingraban** [comment]
Auch unser Install-Tool erstellt gewisse Tabellen und Prozeduren händisch, wenn sie noch nicht vorhanden sind.
Das hat Christopher damals so implementiert.
Ich gehe davon aus, dass er das gleiche Problem damit lösen wollte - ich starte den Installer zum ersten mal auf einer komplett leeren Datenbank.

**Comment by scholz-afis** [comment]
> Auch unser Install-Tool erstellt gewisse Tabellen und Prozeduren händisch, wenn sie noch nicht vorhanden sind.

Läuft das *Install-Tool* auch innerhalb eines CAS-Containers oder wie wird dieser Schema-Update automatisiert bewerkstelligt?

* Wieso eine Service-Bean beim Nicht-Vorhandensein von Datenbank-Tabellen sterben muss, ist mir nicht schlüssig, außer die hierzu notwendige Fehlerbehandlung wurde bisher nicht realisiert.
* Ich würde vorschlagen auf eine eigene Lösung zur Erstellung von Tabellen zugunsten von [Liquibase](https://www.liquibase.org/) oder [Flyway](https://flywaydb.org/) zu verzichten. Ein Investition von Entwicklerzeit für ein prinzipiell schon längst gelöstes Standard-Problem (Versionsverwaltung für DB-Schemas und automatische Aktualisierung) erscheint mir nicht sinnvoll.

**Comment by martins-1992** [comment]
>     * Wieso eine Service-Bean beim Nicht-Vorhandensein von Datenbank-Tabellen sterben muss, ist mir nicht schlüssig, außer die hierzu notwendige Fehlerbehandlung wurde bisher nicht realisiert.

Wurde bisher nicht realisiert.
