### ISSUE TITLE
Logger für allgemeine Infos 

### ISSUE THREAD

**Issue by janiak-minova** [minova-afis/aero.minova.cas#656]
Die aktuell möglichen Logger  (SqlLogger, PrivilegeLogger, ErrorLogger, UserLogger, FilesLogger, SetupLogger, QueueServiceLog) decken nicht alle möglichen Fälle ab. Es sollte einen Logger geben, der für allgemeine Informationen genutzt werden kann, vor allem von Extensions.

Abrechnung={XXX/XXX/XXX/ZPROGRAM}

**Comment by martins-1992** [comment]
Für Prozeduraufrufe und somit Extensions kann man, meines Wissens nach, den SqlLogger verwenden.

**Comment by martins-1992** [comment]
Ich glaube, dass der SQL-Logger nicht nur für SQL verwendet wird.

**Comment by martins-1992** [comment]
Hier ein Beispiel: https://github.com/minova-afis/aero.minova.invoice.oiltanking/blob/2d898d4b6f024500923c372a52e4fcef58edc23d/server/src/main/java/aero/minova/invoice/oiltanking/sap/SapSender.java#L98

Heisst nicht, dass es gut ist und man nicht einen Info-Logger einführen könnte.
