### ISSUE TITLE
CAS blockiert sich selbst

### ISSUE THREAD

**Issue by weber-minova** [minova-afis/aero.minova.cas#679]
Aus Issue #657 : In UserPrivilege habe ich es geschafft, das CAS komplett zu zerstören, indem ich folgendes gespeichert habe

Das CAS blockiert sich selbst, wenn es versucht Updates/Deletes auf seine eigenen Tabellen auszuführen, und verursacht dadurch TimeOuts.
Nicht nur, dass diese TimeOuts auftreten, die Prozedur wird auch nicht ausgeführt.

Meine Idee wäre jetzt, einfach alle CAS Prozeduren über Extensions -> JPA auszuführen.

**Comment by martins-1992** [comment]
Verstehe das Problem nicht ganz.

**Comment by weber-minova** [comment]
Hier noch ein Issue mit StackTrace, was uns vielleicht bei der Analyse mehr helfen kann: https://github.com/minova-afis/com.minova.som97286.freetables/issues/41

**Comment by janiak-minova** [comment]
Sollte sich mit https://github.com/minova-afis/aero.minova.cas/pull/846 erledigt haben.
