### ISSUE TITLE
App-Projekt-Abhängigkeitsverwaltung verbessern

### ISSUE THREAD

**Issue by martins-1992** [minova-afis/aero.minova.cas#712]
Entstanden aus: https://github.com/minova-afis/aero.minova.cas.plugin.attachments/pull/138

**Beschreibung:**
Es geht darum, dass die richtigen Jars in den Container des Kundenprojekts kommen.
Hier geht es noch nicht darum, dass System grundlegend zu verändern:

* [x] Doku durchlesen und eventuell veraltete Stellen aktualisieren. Hier sollten mindestens @weber-minova @martins-1992 und @Bauer-David dabei sein. Anschließend mit @janiak-minova und @scholz-afis durchgehen.
   * [x] Wird packaging jar in der POM wirklich benötigt? Kann man über die effektiv POM prüfen. -> In der Doku steht kein packaging jar für Extensions. Ich nehme erstmal, dass es nicht notwendig ist (https://github.com/minova-afis/aero.minova.cas/blob/main/service/doc/adoc/extensions.adoc). Für App-Projekte wird in der Doku explizit hingewiesen, dass kein packaging gesetzt werden sollte: https://github.com/minova-afis/aero.minova.app.parent/blob/main/doc/adoc/pom.adoc
* [ ] Von @ingraban vorgeschlagen: die CAS-Version nicht in den Dockerfiles getrennt vom Rest bestimmen, sondern dies anhand von Maven erledigen. Hier könnte man den Open-Source-CAS-Teil so erweitern, dass in dem Basis-App-Projekt, welches von allen App-Projekten verwendet wird, auch die Jars vom CAS-Dienst vorhanden sind. Falls dies eine Lösung wäre und umgesetzt werden sollte, würde man die CAS-Version nicht mehr im Dockerfile angeben und würde ein allgemeines Image verwenden, welches größtenteils nur Java enthält.
* [ ] #724
* [ ] Ein anderes Parent für CAS-Extensions verwenden. Es sollte eventuell, dass gleiche Parent wie CAS sein.
    Über `${project.version}` könnte dann sichergestellt werden, dass das Parent und die CAS-Dependency dieselbe Version haben.

@scholz-afis @ingraban @weber-minova @janiak-minova Was ist eure Meinung dazu?

**Beispiel/ Mockup:**

Abrechnung={XXX/XXX/XXX/ZPROGRAM}

**Comment by janiak-minova** [comment]
>  @janiak-minova und @scholz-afis haben angemerkt, dass bei Extensions und dessen dazugehörigen App-Projekt jeweils die CAS-Version gleich sein müssen und entsprechend gepflegt werden müssen.

-> Das betrifft nicht nur die CAS-Version, sondern alle unsere Projekte, die wir auch als Abhängigkeit verwenden.

Eventuell könnte man bei dem letzten Punkt auch versuchen, die third-party-libaries im CAS loszuwerden, die nicht vom CAS aber von Extensions benötigt werden.

**Comment by martins-1992** [comment]
> > @janiak-minova und @scholz-afis haben angemerkt, dass bei Extensions und dessen dazugehörigen App-Projekt jeweils die CAS-Version gleich sein müssen und entsprechend gepflegt werden müssen.
> 
> → Das betrifft nicht nur die CAS-Version, sondern alle unsere Projekte, die wir auch als Abhängigkeit verwenden.
Habe es im Issue angepasst.

> Eventuell könnte man bei dem zweiten Punkt auch versuchen, die third-party-libraries im CAS loszuwerden, die nicht vom CAS, aber von Extensions benötigt werden.

Hier ist das Problem, dass es mit der Zeit bei steigender Anzahl an third-party Bibliotheken es sehr schwer wird, diese ohne Überschneidungen zu definieren, wenn diese nicht zentral (bspw. CAS) definiert sind.
Wenn es Überschneidungen gibt, werden diese wiederum mit sehr hoher Wahrscheinlichkeit unterschiedliche Versionen haben,
wenn diese jeweils in eigenen Modulen vorhanden sind.

Aus diesem Grund würde ich es erstmal bevorzugen, diese Abhängigkeiten im CAS direkt anzugeben.

**Comment by martins-1992** [comment]
@janiak-minova Hat die Anpassungen des Kundenprojekts,
dass Problem mit den doppelten Jars behoben?

**Comment by martins-1992** [comment]
@janiak-minova @weber-minova Die [Step by step -Anleitung](https://github.com/minova-afis/aero.minova.cas/blob/main/service/doc/adoc/extensions.adoc#step-by-step---anleitung) ist gut.

**Comment by martins-1992** [comment]
Rico ist sich nicht sicher, was er damit machen kann,
aber seine Intuition, sagt ihm, dass dieses Issue nützlich sein könnte.

Rico übernimmt das  Issue.

**Comment by martins-1992** [comment]
Wurde mit #800 umgesetzt.
