### ISSUE TITLE
Extension und App-Projekt zusammenführen.

### ISSUE THREAD

**Issue by martins-1992** [minova-afis/aero.minova.cas#724]
Ursprüngliche Beschreibung:

``````

 @janiak-minova und @scholz-afis haben angemerkt, dass bei Extensions und
dessen dazugehörigen App-Projekt jeweils die CAS-Version und
die Abhängigkeiten-Version jeweils gleich sein müssen und entsprechend gepflegt werden müssen.
Das ist fehleranfällig.
Mein Vorschlag: App-Projekte könnten auch den Source-Code für Extensions enthalten.
So hätte man eine POM dafür, welche entsprechend einfacher gepflegt werden könnte,
indem dazu Properties verwendet werden.
Der Aufwand (größtenteils Parent-POMs anpassen) dazu wäre wahrscheinlich etwas groß (wird bei mir zeitlich erstmal nichts).


``````

Die Aufteilung in Extension und App-Projekten führt zu Problem:
* Die Versionen von den Abhängigkeiten müssen synchron gehalten werden, was mit Maven nativen mittel nicht einfach möglich ist.
* Die Aufteilung verdoppelt die Anzahl der Projekte, was das Ganze umständlicher macht.

**Comment by martins-1992** [comment]
Folgender Quick-Hack wäre unter Umständen möglich, wo ich nicht weiss, was für Probleme man dabei finden würde:
* Nehmen wir an wir haben für ein Projekt, ein App-Projekt und ein Extension-Projekt.
* Wir verschieben den Java-Code und die CAS-Abhängigkeit aus dem Extension-Projekt direkt in das App-Projekt.
    Danach löschen wir das Extension-Projekt.
   Beim Release sollte auch bereits jetzt (das ist eine Vermutung) in den Jars ohne den app Classifier der Code in der Release-Jar stehen.
* Das App-Parent so erweitern, dass beim Build des Container-Images die Jar ohne app Classifier in den Extension-Ordner kopiert wird.

@ingraban @scholz-afis @weber-minova @janiak-minova  Was haltet ihr von diesem Weg App-Projekte und Extension-Projekte so in ein Projekt zu packen? Leider weiss ich nicht, ob das so einfach ohne Probleme geht.

**Comment by scholz-afis** [comment]
Puuuh, wo soll ich da anfangen? Ich glaube, dass die Entwickler von *Maven* und *Gradle* eine einfache Möglichkeit im Sinn hatten, Abhängigkeiten von Projekten zu verwalten. Sicher ist der Ist-Zustand der Verwaltung von CAS-basierenden Kundenprojekten objektiven und rationalen Entscheidungen geschuldet, die jedoch aus Meiner Sicht zu folgenden Problemen führen:

* Nicht alle Submodule (`app`) sind nicht von der Parent-POM abhängig. Per Definition sind das dann auch keine Submodule, die in ein einziges Repository gehören.
* Sourcecode (`client/helpers`) für das Frontend (*WFC*) ist Bestandteil vom Backend-Repository. Dadurch wird der Release-Prozess konterkariert, da der ClientHelper nur als SNAPSHOT "released" werden kann.
* Resourcen (z.B. `forms`, `images`, `tables`, ...) werden nicht im `resources` Verzeichnis platziert, sondern werden als exotisches Submodule `app` geschnürt.
* Submodule (`cas.service`) führen Dependencies ein, die es nicht 'mal selbst benötigt.
* Dependencies gelangen nicht über den Dependency-Tree in die Application, sondern über das exotische Submodule `app` mittels unkontrollierbare Kopieraktionen. Das verhindert die Kontrolle auf sich widersprechende Dependencies (z.B. *maven-enforcer-plugin*)
* Das [Generieren von CAS-Projekt-kompatiblen Bibliotheken](https://github.com/minova-afis/aero.minova.os.github.workflows/issues/2) aus einer OpenAPI Spezifikation ist bei allen Standard-Maven-Projekten ein Aufwand von <1h. Bei CAS mit diesem `app`-Submodul hat mich der Umbau über **eine Woche** Zeit gekostet, da an der Projektstruktur, Inhalt von Dateien und Workflows herumgebastelt werden musste.
* Ein Umstieg von *Maven* auf z.B. *Gradle* zieht einen hohen Anpassungsaufwand nach sich. (Nicht, das ich auf *Gradle* umsteigen würde, aber es geht um das Verbauen von Möglichkeiten, wenn keine "normale" Projektstruktur verwendet wird.  
* ...

@martins-1992 Kurz: Ja, ich bin dafür `app` in dem von Maven gedachten Workflow zusammenzuführen, allerdings immer genau so, wie ein Standard-Maven-Projekt aufgebaut sein sollte. Für die Minova-spezifischen Erfordernisse (z.B. CAS muss JARs für WFC vorhalten) würde ich Lösungen finden, die der Projekt-Struktur nicht in den oben genannten Punkten zuwiderläuft.

**Comment by martins-1992** [comment]
Rico sieht das als gute Basis.

**Comment by janiak-minova** [comment]
> Rico sieht das als gute Basis.

Wer ist Rico?

**Comment by martins-1992** [comment]
Rico kommt Anfang nächsten Jahres.

**Comment by martins-1992** [comment]
Ist mit CAS 13 umgesetzt.
