### ISSUE TITLE
CORS Policy für DEV und PROD

### ISSUE THREAD

**Issue by scjminova** [minova-afis/aero.minova.cas#767]
ALS: Developer
MÖCHTE ICH: Dass das CAS Zugriffe von den Origins unserer Web-Front-Ends zulässt.
SO DASS: Die Web-Front-Ends mit dem CAS kommunizieren können

**Details:**
- Für die Entwicklung ist es wichtig `http://localhost:8100` und `https://saas-app-dev.minova.com` freizugeben
- Für die PROD-Umgebung: `https://saas-app.minova.com`

![Bildschirmfoto 2023-10-18 um 15 17 02](https://github.com/minova-afis/aero.minova.cas/assets/108717569/83ca1692-cc7a-49fd-9d29-48ce770f0eee)

Abrechnung={XXX/XXX/XXX/XXX}

**Comment by scjminova** [comment]
DAs wäre der application.property-Eintrag: cors.allowed.origins:

**Comment by weber-minova** [comment]
@scjminova das kann mittlerweile geschlossen werden, oder?
