### ISSUE TITLE
Erweiterung CAS um die Möglichkeit, den JobExecutor-Dienst mit Parametern aufzurufen

### ISSUE THREAD

**Issue by theuerer** [minova-afis/aero.minova.cas#862]
**Beschreibung:**
Aktuell ist es nicht möglich mit dem CAS, Jobs auszuführen.

**Beispiel/ Mockup:**
Für die Erstellung von XML-Rechnungen gibt es einen Job im 11-er SIS. Das CAS kann keine Jobs durchführen.
Die Idee wäre nun, dass das CAS den JobExecutor (des AFIS z.B.) mit dem Job "XMLInvoice" und dem InvoiceKey aufruft.

Abrechnung={XXX/XXX/XXX/ZPROGRAM}

**Comment by martins-1992** [comment]
Für die Besprechung: wie ist der Stand von `aero.minova.jobdefinition`?

**Comment by CE7** [comment]
* OILT verwendet keinen JobExecutor

_Idee_

* CAS sendet eine Nachricht an den JobExecutor 
* Abhängigkeit nicht auf das ch.minova.data.schema
* Alte Jobs bleiben in der selben Konfiguration wie im 11er Stand
 * Jobdefinition bleibt in der SQL-Datenbank
* CAS kommunizieren mit dem JobExecutor? --> 

Wenn wir aus der Anwendung einen Job manuell ausführen wollen (Wiederholtes Ausführen einer Tagesliste, im super-Modus) muss das CAS den JobExecutor anstoßen. Hier können wir nicht wie im 11er Stand einfach ein Event senden odern müssen folgende Kommunikation [link](https://teams.microsoft.com/l/message/19:meeting_YTgyZTY1MmQtZmM2Ny00M2ViLTg0ZTctYTkxN2RlNmIzOGRj@thread.v2/1706689005395?context=%7B%22contextType%22%3A%22chat%22%7D) verwenden

**Comment by martins-1992** [comment]
Ich habe mit Christopher gesprochen:
Es soll der [JobExecutorController ](https://github.com/minova-afis/aero.minova.service.jobexecutor/blob/main/extension/src/main/java/aero/minova/service/jobexecuter/extension/controller/JobExecutorController.java) verwendet werden, wobei dieser für Verwendung durch andere Extensions noch angepasst werden muss.

Um es einfach zu gestalten, wollen wir den Mechanismus aus dem 11er SIS bzgl. der XML-Datei übernehmen.
Eine mögliche Umsetzung sollte entworfen und mit mindestens @martins-1992 und @janiak-minova besprochen werden.

**Comment by Bauer-David** [comment]
> Ich habe mit Christopher gesprochen: Es soll der [JobExecutorController ](https://github.com/minova-afis/aero.minova.service.jobexecutor/blob/main/extension/src/main/java/aero/minova/service/jobexecuter/extension/controller/JobExecutorController.java) verwendet werden, wobei dieser für Verwendung durch andere Extensions noch angepasst werden muss.
> 

Welche anderen Extension und welche Anpassungen müssen gemacht werden?

**Comment by janiak-minova** [comment]
Ich denke, eine große Entscheidung, die wir treffen müssen ist, ob wir weiterhin SQL-Prozeduren für den JobExecutor verwenden wollen.
Und ob wir Unabhängig von data.schema werden sollen. 

Vorteil wäre, dass wir z.B. auch eine Postgres Datenbank anbinden können. Außerdem wäre der JobExecutor dann auch in "kleineren" Anwendungen einsetzbar, ohne dass wir gleich unser komplettes data.schema einspielen müssen.

Ich kenne leider den JobExecutor nicht gut genug um zu wissen, ob an diesem Änderungen notwendig wären, um das umzusetzen.

Außerdem besteht soweit ich weiß kein Plan, das SIS auf CAS13 umzustellen, was die Entwicklung der Extensions stark vereinfachen würde.

**Comment by janiak-minova** [comment]
> Um es einfach zu gestalten, wollen wir den Mechanismus aus dem 11er SIS bzgl. der XML-Datei übernehmen.

Geht es hier um die param-String Felder? Diese werden vom WFC bereits unterstützt, soweit ich weiß hat die JobDefinition auch bereits einen Helper, der sich darum kümmert.

**Comment by Bauer-David** [comment]
Hier wäre eine Besprechung mit allen Beteiligten das beste. Es wird wieder nur mit der Hälfte geredet und dann weiter gereicht.

**Comment by martins-1992** [comment]
Ich würde dann einladen. Muss noch überlegen, wann.

**Comment by CE7** [comment]
habe eingeladen. Di. 14.02.24 14-15Uhr

**Comment by CE7** [comment]
Es muss ein InvoiceController erstellt werden, dieser kann dann die einzelnen Schritte ausführen 
* BeforeInvoice
* DuringInvoice
* AfterInvoice

**Comment by martins-1992** [comment]
So wird für die Oiltanking das Invoice in einer CAS-Extension ausgeführt: https://github.com/minova-afis/aero.minova.invoice.oiltanking/blob/26bbd2b3595a0afdd0575c0637907d34a455f5f7/server/src/main/java/aero/minova/invoice/oiltanking/InvoiceOiltankingExtension.java#L82

**Comment by CE7** [comment]
Idee: 
In den xtCasProperties steht die Invoice-Prozedur auf die sich dann registriert wird. Damit entscheiden wir ob wir "nur" den InvoiceController verwenden oder einen speziellen.

**Comment by wis36** [comment]
Zum Nachlesen: in der Besprechung hatten wir auch über die [CAS-Extension für den JobExecutor](https://github.com/minova-afis/aero.minova.service.jobexecutor?tab=readme-ov-file#jobexecutor-extension-verwenden) gesprochen.

**Comment by martins-1992** [comment]
* [ ] Herausfinden, welche Prozedur beim Buchen verwendet wird.
* [ ] Extension für die Prozedur erstellen.
* [ ] Allgemeine Buchungsfunktion implementieren:
    * [ ] Prozedur aus `xtcasProperies#xpcorCloseInvoiceProcedure` ausführen.
    * [ ] Default `xpcorCloseInvoiceDefault` implementieren.
        * [ ] BeforeInvoice-Jobs
        * [ ] Die eigentliche Buchung
            * [ ] Standard-PDF mit BIRT erstellen. Siehe Oiltanking-Invoice.
        * [ ] AfterInvoice-Jobs
* [ ] Neue Buchungsimplementierung testen.
* [ ] Neue Buchungsimplementierung in Düsseldorf installieren

**Comment by CE7** [comment]
Mit THG noch besprechen, wie mit dem Kunden kommuniziert werden soll. Mini-Schulung damit der Anwedner bescheid weiß.

**Comment by martins-1992** [comment]
* [ ] Beim Zurücksetzen der Rechnung muss die PDF gelöscht werden.

**Comment by wis36** [comment]
Ist das tatsächlich so gewollt? Bei uns intern hatten wir das extra nicht gemacht, dachte ich.

**Comment by martins-1992** [comment]
@wis36 Das Löschen setzt der BIRT-Dienst um.
Dieser verschiebt die PDFs standardmäßig in einen deleted-Ordner.
Sie werden also nicht wirklich gelöscht.
Man kann aber auch alternativen implementieren (bspw. das mfiles Backend).
